apiVersion: v1
kind: Service
metadata:
  name: tomcat
  labels:
    app: tomcat-api
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: api
  selector:
    app: tomcat-api
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tomcat
  labels:
    app: tomcat-api
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: tomcat-api
    spec:
      containers:
      - name: tomcat
        image: tomcat:alpine
        ports:
        - containerPort: 8080
          name: api
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx-web
spec:
  ports:
    - port: 8082
      targetPort: 80
      name: nginx
  selector:
    app: nginx-web
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx-web
spec:
  template:
    metadata:
      labels:
        app: nginx-web
    spec:
      containers:
      - name: nginx
        image: neoxen/nginx-with-tomcat:0.0.1
        ports:
        - containerPort: 80
          name: nginx-web
